import type { Metadata } from "next";
import {  Geist_Mono ,Oswald } from "next/font/google";
import "./globals.css";

const geistSans = Oswald({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "200"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${geistSans.variable} antialiased`}
      >
        {/* <h1>我是根layout</h1> */}
        {children}
      </body>
    </html>
  );
}
